name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linting
        run: echo "Linting step runs here"

      - name: Run tests
        run: echo "Testing step runs here"
